### ISSUE TITLE
Q3

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/paparazzi#1]
For my Q3 I had the mission of bringing Paparazzi closer to a "real" server implementation. For that there some "best-first-steps" to follow:
- a considerable amount of time per call goes in running the modify version tangram-es. To then wait until it's over. The solution for that is to leave the program (with it OpenGL ES content) running. That had dramatically advantages, for example: if a new request use the same style as the previous one, there is no need to re parse the new style (YAY!), if the new request is in the same geographic place at the previous one, there is no need to fetch new tiles (double YAY!). 
- Cash the hell of everything. The OPs and Data teams members have a lot of GREAT ideas, expertise and wisdom on this front. Hooray! @zerebubuth was telling me some of those tricks when he was in NYC.
- My "server" use Node.js. Probably is a good idea to port it to Python, just because most of the data scripts seams to be written in that language and I imagine there is all sort of goodies already develop. Yes @rmarianski, be prepare to the avalanche of questions I will send you : )

The last two items are important but need the help of @zerebubuth and @rmarianski. So what I can do in the mid time? Yeap... learn IPC in POSIX OSs. Yay! but Why IPC? 

This is my plan, tangram needs to be open all the time, and I really really don't want to code a multi thread server in C++... that will be bad news for everybody. Instead I want to take advantage of the high level of JS and Python to run different instances of paparazzi (the mod version of tangram-es that take pictures)... each instance will run constantly in a natural new thread lunched by the server. It will be the poor man's version of a multi thread server. But to my plan be successful I need to communicate between the server and paparazzi, sending "commands" to each instance telling them what style should load and where. 

So I did some small test this week with small OpenGL ES C++ program taking commands from the standard CIN. The test were ok, @tallytalwar teach me a lot of new fancy C++11 tricks that makes everything look like JS. Basically I separate a two threads one that do the rendering in the opengl es context and the other that listen to commands... then use a bunch of mutex and "atoms" (yes that's a thing now) to communicate between threads. 

Then I realize that I need to report back from paparazzi to the server, every time a image is done. Big boomer... BUT thanks fully @rmarianski point me to IPCs. So...

... BEHOLD me new subway-reading-material https://www.amazon.com/Advanced-Programming-UNIX-Environment-3rd/dp/0321637739/ref=sr_1_1?ie=UTF8&qid=1471533628&sr=8-1&keywords=advance+programming+in+the+unix The ppl that I bang in the subway ride with this huge book is as happy as me.

Actually that's kind of an exaggeration... I'm happy to learn new things about *inux systems : ) 

So that's all my report for now.

cc @bcamper @blair1618

**Comment by zerebubuth** [comment]
When I've been writing multi-process services before, I've found [zeromq](http://zeromq.org) to be extremely useful. It's also got [libraries in Python, Node, and lots of other languages](http://zeromq.org/bindings:_start) which makes it great for prototyping in a scripting language before profiling to know whether any bits really need to be in C++.

I love zeromq (and so does @kevinkreiser) so feel free to ask me anything!

**Comment by zerebubuth** [comment]
I probably should have mentioned - it's a message passing library, which means it's possible to send and receive messages over the network and/or IPC rather than having to write bytes to a raw socket or worry about mutexes, semaphores and SHM. Personally, I find that a lot easier to reason about than threads, YMMV.

**Comment by patriciogonzalezvivo** [comment]
Thanks @zerebubuth!! I will check it out. 
What's the message passing library name?

**Comment by rmarianski** [comment]
http://zeromq.org/

**Comment by patriciogonzalezvivo** [comment]
Thanks booth! I remebered @rmarianski already talk to me about it. Again thanks.

**Comment by patriciogonzalezvivo** [comment]
Mayor progress today https://github.com/tangrams/paparazzi/commit/094a4ceb6a7f3d87dd8dd5f260fd6d373a31ef68

Paparazzi becomes more reliable, efficient and scalable, while the code got simplify a lot thanks to [`prime_server`](https://github.com/kevinkreiser/prime_server) by @kevinkreiser

It's easy to scale the number of paparazzi_threads... easy like changing a number

It's working on darwin and ubuntu. Next week will be raspbian and the amazon server. 

**Regresions**: no more node.js server that means no HTTPS and no image caching... (there is no use of the file disk at all!!). Both things will be fixed when we add caching up front of the amazon server... that will bring all sort of good things : ) I'm very excited 

Thanks @kevinkreiser long life for PRIME_SERVER !!!

**TODO's**: Compile it on the amazon server and then start thinking in adding this behind https://mapzen.com and the caching up front cc @rmarianski @zerebubuth 

cc @bcamper @blair1618

**Comment by patriciogonzalezvivo** [comment]
Well have been an exciting week so far! Full of synergy! Big thanks to @kevinkreiser @heffergm for the help.

I have fix some memory and efficiency issues, but [encoding the pixels to PNG](https://github.com/tangrams/paparazzi/blob/master/src/paparazzi.cpp#L306-L307) still need some work. Thinking on using `libpng` or research about `openMAX` (although I think works better for decoding video... that encoding a single image)

Beside that `paparazzi_thread`s are working with some hiccups as you can see if you run this tester I call [runway](https://tangrams.github.io/runway/?scene=https://tangrams.github.io/tron/tron.yaml) (hope you notice the theme around industries that hire photographers).

I have to investigate where those glitches are originating on.

[![03](https://cloud.githubusercontent.com/assets/346914/18182548/6ab21986-705e-11e6-8a57-648af00e78cf.gif)](https://tangrams.github.io/runway/?scene=https://tangrams.github.io/tron/tron.yaml)

I'm also start taking benchmarking more seriously. Runway calculates an speed average of **millisecond per pixel** (you can see it by opening the console) between the moment it send the call until it gets the image. 

Planning to add the same, to the server.

But still this unit is very insufficient to explain what's going on. For example, if the worker was to change styles... boom is like 0.3 seconds for a simple style like https://tangrams.github.io/tangram-sandbox/styles/default.yaml... also tangram-es was to load tiles.... so if there are images on the same place and same style is faster.

A good taks to do together with @rmarianski  or @zerebubuth is to make a modify version of `prime_proxy` that distribute the load across the workers (`paparazzi_thread`) so it will try to assign to each one a task that is likely to perform faster. For example if worker 1 was a `tron.yaml` scene file loaded... assign to him other `tron.yaml` calls.

Time ago @bcamper was suggesting to have workers with fixed scenes loaded. For example a worker only do `refill`, other `walkabout`, other `tron`, etc. 

Any way, next step for me is to find where the glitches are comming... and how we can make it fast.

**Comment by patriciogonzalezvivo** [comment]
Hi paparazzis!

The good news are that @rmarianski will join officially to the **paparazzi team**. YAY! 
Bad news for me he is in vacation. So... while he is reloading his batteries I'm doing more speculative/testing work about this beautiful service we are putting together.

What do I mean with speculative? I have been thinking on POST request. Until recently paparazzi only handle GET calls. But I can imagine a lot of uses for sending snapshots of a "ongoing" map, something that is not up there in the cloud yet... Putting the .yaml scene files in a POST body seams like a first step to explore this.

So I start working on this https://github.com/tangrams/paparazzi/commit/68dff50561917ed681a8f2259a45ed8cd0294c5b. I end up defaulting in some old habits... to go around problems.

What was the main problem? well Tangram-es is not designed to load YAML scene as strings (only as url to files). I already ask @tallytalwar for that feature (cc @blair1618). Until that is implemented and merge on tangram will take it's own time (this is definitely not a priority, given the other important goals they have). 

So temporally I'm going around this by doing the caching trick I was doing before. Save the yaml to a file which name is generated with a MD5. If the files already exist don't spend time saving it again... and also prevent for calling the `loadScene` several times for the same scene.

The obvious down side of this is saving/reading from/to disk is slow and inconvenient (takes space from the server disk and we need to be watching it to avoid over fill it).

Does anybody have a good advice for this? Is there any `StringIO` equivalent for C++. @rmarianski @zerebubuth @kevinkreiser 

So no this is working... my next step is to build a small app to test this POST request. I will go with something custom, handy that potentially can make a hell a lot of different request : )

Thanks

cc @bcamper

**Comment by zerebubuth** [comment]
Writing to disk is slow, but probably faster than reading a tile over the network, so I wouldn't worry about it too much. If profiling later shows that it's a problem, worry about it then :smile: 

As for `StringIO`, the equivalent class in C++ is called [`stringstream`](http://www.cplusplus.com/reference/sstream/stringstream/).

**Comment by patriciogonzalezvivo** [comment]
So true! thanks @zerebubuth !

**Comment by patriciogonzalezvivo** [comment]
`POST` request are coming along, @tallytalwar just told me tangram-es now support scene loading from strings, so I will add that tomorrow, after meeting with @rmarianski and start thinking on times/goals/steps to make paparazzi a official `::dev::` project with eyes on `::prod::`. Hooray!

To test `POST` request I made another tool that use paparazzi call [FieldGuides](https://github.com/tangrams/fieldguide). This runs as a service and through a python script construct [PDFs](https://github.com/tangrams/paparazzi/files/473055/route.pdf) on request of Turn-By-Turn routes, with images of every direction.

Currently running in http://54.209.198.36/ (you need to hit the "download button") to see the pdf.

In the future we can send it by mail directly to a  the kindle using this [this email-to-kindle amazon  service](https://www.amazon.com/gp/sendtokindle/email)

![00](https://cloud.githubusercontent.com/assets/346914/18523849/0a03e7b0-7a84-11e6-8e21-d5e34a352341.gif)

Exciting! right?

**Comment by nvkelso** [comment]
THIS IS THE BEST :)

**Comment by patriciogonzalezvivo** [comment]
Hi! So this week we start talking with @rmarianski and brain storming on architectural improvements to the project, while he works on creating a stack for paparazzi.

So far the strategies goes in two fronts:
- delivering resources faster: probably by providing mapzen tiles faster (we own them... right?)
- preventing `paparazzi_workers` to spend so much time parsing scene files: modifying @kevinkreiser `prime_proxy` to keep track of the last styles of the `paparazzi_worker`s and try to match new style-request with the workers that already had it parsed... like a matching algorithm... haaa... love in the cloud : )

Beside this thinking we were doing. I update `paparazzi_worker` to use the last tangram-es version... which just did a huge change by abstracting OpenGL ES, and that break a lot of things... thanks @blair1618 @tallytalwar @hjanetzek  for a week of fun.
Good news are that that give me time to review and polish details... particularly the weird glitching was happening every now and then in the amazon server... was looking like some sort of depth buffer bug... and it was. The RaspberryPi was a lot of help in that front... since some versions ago, paparazzi wasn't rendering correctly on the RPI... and the reason was that rendering the depth buffer to a texture wasn't making it happy. So I replace the rendering to texture for a plain depth render buffer to draw to and all happy-ever-after. This seams to make the Amazon server also happy. Other tweaks are some improvements on the use of resources... like reducing the numbers of call when they are not need.

That's all for this week. Excited for the new stack

**Comment by kevinkreiser** [comment]
wrt modifying the proxy, should be easy since you can just derive your own proxy class and mess with the guts. i wonder though if it might be a good idea for me to break up the worker and proxy classes a bit so that you can more easily inject your functionality. specifically i could turn the heartbeating of the worker into a function on the worker class, then you could inject functionality there. and i could turn the choosing of a worker by the proxy into a function and you could do some more work there? this would be pretty easy changes from my point of view so let me know if this is something that sounds desirable @patriciogonzalezvivo @rmarianski @zerebubuth

**Comment by kevinkreiser** [comment]
looks like the worker already has an `advertise` function so you'll be able to just overload that with information about styles a worker might be faster at working on. so i guess the only thing i might do is change the proxy to have a more flexible/overridable way of choosing which worker to forward work to

**Comment by patriciogonzalezvivo** [comment]
@kevinkreiser !! WOW!! making easier to add a custom "picking" function on the `proxy` together with a way for the `worker` that is available for work and the last parsed scene will be a huge deal. I can tinker around that to force the proxy to to try to match a scene, if the matching doesn't work will assigned to a random worker... or even better assigned to a worker that doesn't have a "priority" style.... right... I can add a list of "priority" styles, like the once we support officially (refill, tron, walkabout, etc)

What are you thought on this?

**Comment by kevinkreiser** [comment]
@patriciogonzalezvivo yeah i think it will be quite easy for you to inject that functionality in  your proxy once i make a few cosmetic changes to its interface. give me a bit and ill take a whack at it.

**Comment by patriciogonzalezvivo** [comment]
synergy is happening

**Comment by kevinkreiser** [comment]
ok ive set up a sketch to make this possible at kevinkreiser/prime_server#51

**Comment by patriciogonzalezvivo** [comment]
Awesome! 👍  👍  thanks!

**Comment by patriciogonzalezvivo** [comment]
Preparing things for `paparazzi_proxy after`@kevinkreiser's finish his work on `prime_proxy` https://github.com/tangrams/paparazzi/pull/5

**Comment by patriciogonzalezvivo** [comment]
Teaching paparazzi to make tiles https://github.com/tangrams/paparazzi/pull/6

**Comment by patriciogonzalezvivo** [comment]
Here is a small simple project to show case the new paparazzi's tile rendering capabilities https://tangrams.github.io/obituary/#4/-24.97/-62.53

![2016-10-04 12_10_48](https://cloud.githubusercontent.com/assets/346914/19082319/a21d47ce-8a2b-11e6-9128-e86a7f934b99.gif)

**IMPORTANT DISCLOSURE**: this tiles will not show correctly on higher zoom levels (specially with extruded buildings) and you probably will notice chopped labels : ( 
@zerebubuth have way more experience on that front, this is mostly a tool to check the performance on same-size-images/same-style paparazzi request
