### ISSUE TITLE
1x or 2x output images?

### ISSUE THREAD

**Issue by nvkelso** [tangrams/paparazzi#12]
Does this output 2x retina images or 1x basic images? Is there a configuration for this?

**Comment by patriciogonzalezvivo** [comment]
A `density=1` / `density=2` argument on the query will make sense? I'm open to other names for it

**Comment by nvkelso** [comment]
I've seen `scale` used for this as well, but pixel `density` makes a lot of sense to me.

**Comment by patriciogonzalezvivo** [comment]
Understandably tangram-es don't handle multiple changes on pixel scale at the moment. Making an issue for it https://github.com/tangrams/tangram-es/issues/1071

Until this is done I will live this here: https://github.com/tangrams/paparazzi/tree/pixeldensity_flag

**Comment by nvkelso** [comment]
Neat! Can you post some example images and @2x density URLs, please?

**Comment by patriciogonzalezvivo** [comment]
Will be like: `http://paparazzi.dev.mapzen.com/?lat=40.7053&lon=-74.0098&zoom=4&width=1000&height=1000&density=2&scene=https://tangrams.github.io/refill-style/refill-style.yaml`

Is not in production yet, only in old server. @rmarianski can you give me a hand with that?

**Comment by patriciogonzalezvivo** [comment]
Here is a link to my dev server https://static-maps.dev.mapzen.com/?lat=40.7053&lon=-74.0098&zoom=4&width=1000&height=1000&density=1&scene=https://tangrams.github.io/refill-style/refill-style.yaml

**Comment by patriciogonzalezvivo** [comment]
`density=1`
![density1](https://cloud.githubusercontent.com/assets/346914/20541956/61dddcb4-b0cd-11e6-921e-8c36b3943937.png)

`density=2`
![density2](https://cloud.githubusercontent.com/assets/346914/20541957/61dfc038-b0cd-11e6-9e4c-59f985174fec.png)

**Comment by nvkelso** [comment]
Super cool! 

Why are there all the light grey text on the map? Those are region names, but aren't in production Refill (see screenshot from prod below at zoom 4 for similar crop):

<img width="896" alt="screen shot 2016-11-22 at 13 06 10" src="https://cloud.githubusercontent.com/assets/853051/20542024/92a03522-b0b4-11e6-881a-5fa109c5842d.png">

**Comment by patriciogonzalezvivo** [comment]
not sure, I will research...

**Comment by rmarianski** [comment]
> Is not in production yet, only in old server. @rmarianski can you give me a hand with that?

Sure thing. Ping me tomorrow and we'll sort it out.

**Comment by patriciogonzalezvivo** [comment]
@nvkelso ... so doing some research I found the same behavior in TangramES. Talking with @blair1618, we first want to eliminate the chances of a "filter" problem... do you happen to know what lines on the scene YML file are associated with those levels at zoom 4 ??

<img width="951" alt="screen shot 2016-11-28 at 1 37 07 pm" src="https://cloud.githubusercontent.com/assets/346914/20681043/c6272152-b56f-11e6-8ebc-aca59240c6ad.png">

**Comment by nvkelso** [comment]
@patriciogonzalezvivo looks like:

- https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/refill-style-more-labels.yaml#L4121-L4133

**Comment by matteblair** [comment]
@nvkelso The layer you're pointing out here seems like it _should_ be visible (`global.text_visible_admin` is `true`). Am I missing something?

**Comment by nvkelso** [comment]
The visible on Tangram ES region names [source](https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/refill-style-more-labels.yaml#L4127) their text from `name:short` via this global:

https://github.com/tangrams/refill-style-more-labels/blob/gh-pages/refill-style-more-labels.yaml#L22-L25

Looks like Tangram JS correctly says "nothing to see here, skip drawing feature" when `name:short` is false, where Tangram ES is falling back to `name`?

**Comment by tallytalwar** [comment]
Yup @nvkelso you are right on this.

In ES code we are setting the text's source default as the `name` property.
https://github.com/tangrams/tangram-es/blob/master/core/src/style/textStyleBuilder.cpp#L292

This matches the behavior described in the docs:
https://github.com/tangrams/tangram-docs/blob/1d0d68a14b6548c71778cd2aa529aa3ddea0399e/pages/draw.md#text_source

**Comment by nvkelso** [comment]
So it's evaluating as if it is:

`text_source: [name:short, name]`

even though I've specified it as:

`text_source: [name:short]`

I think this is an ES error? Can you file a bug, please?

**Comment by matteblair** [comment]
Yeah, this seems like some kind of bug in ES. Specifying `text_source: 'name:short'` (which should be equivalent here) produces the same behavior as in JS.

**Comment by nvkelso** [comment]
Let's track the Tangram ES bug with https://github.com/tangrams/tangram-es/issues/1108.

**Comment by nvkelso** [comment]
Closing this issue as it seem like it's done (and split related Tangram ES bug into it's own issue upstream).
