### ISSUE TITLE
Paparazzi proxy

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/paparazzi#7]
Now that @kevinkreiser add some sweet customizable widget to `prime_proxy` https://github.com/kevinkreiser/prime_server/pull/52 is time to create a custom `paparazzi_proxy`

How It will work? If I follow @kevinkreiser code correctly:
- `paparazzi_worker` will return a heart beats back to the proxy carry extra information (the url of the last parsed YAML scene file)
- `prime_proxy` will be replace buy a `paparazzi_proxy`, that will parse the query of the HTTP call and extract the required url of the YAML scene file. Then will iterate through the list of heart beats of the workers and see if there is one that match the url. If so, **bang!** we win the right for the request.

That makes sense @kevinkreiser right?

**Comment by kevinkreiser** [comment]
if i were implementing this i would make the worker respond with as little information as possible that still solves the problem.

so if your request were like:  `http://blah.com/give_me_stuff?foo=bar&baz=qux&scene=some_location_some_where`

and only the scene part is relevant. then i would have the worker only send back: `scene=some_location_some_where`

and then in the `paparazzi_proxy` i would wouldnt even parse the full request, i would just treat it as a string search by doing something like `auto found = std::search(request.begin, request.end, heartbeat.begin,heartbeat.end)` and then `if(found != request.end)` i would `return &heartbeat` signifying we found a match.

**Comment by kevinkreiser** [comment]
if you are expecting really large requests (ie ones that come with post bodies) you may also want to not search all the way to `request.end` but rather find where the post body starts and make that the end of the range you want to search. of course if you need to actually look at the stuff in there then by all means parse the full request in the proxy its not **that** expensive.

**Comment by patriciogonzalezvivo** [comment]
I was thinking avoiding POST request at the beginning... but later to match the the worker url I need to make a md5 of it : /

Do you think thats viable?

**Comment by patriciogonzalezvivo** [comment]
@kevinkreiser's custom proxy feature is done and now is compiling correctly on MacOS!! YAY In a glimps I was hable to put together a `paparazzi_proxy`!!! YAY https://github.com/tangrams/paparazzi/commit/3c48add36866f97c8ad1b64b95e19db13e6641e8 Now need some testing

psd: @kevinkreiser can you take a look to my implementation (you will note a lot of copy pasting : ) thanks for that!)
