### ISSUE TITLE
Paparazzi Stack

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/paparazzi#8]
@rmarianski start working on a Paparazzi Stack with a reliable ELB on our Amazon servers. One of the issues he is working on is on the logistic around maintaining and scaling it.

**Comment by patriciogonzalezvivo** [comment]
If I understand well, one of the issues he is addressing is a clear set of chef recipes, for that he is working on rpm packages for all the binaries here https://github.com/tangrams/paparazzi/issues/9

**Comment by patriciogonzalezvivo** [comment]
@rmarianski made a lot of progress here... now is more about making the cheff recipes.

**Comment by rmarianski** [comment]
Yes, working on getting the recipes in place now to deploy all the pieces together.

**Comment by patriciogonzalezvivo** [comment]
@rmarianski jam all this issues! thanks!
