### ISSUE TITLE
RPM packages for paparazzi binaries and dependencies 

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [tangrams/paparazzi#9]
@rmarianski is working on figuring out how to have an Amazon Linux AMI on docker. His plan is to use circles or travis to have continuos integration on Paparazzi binaries and some of their dependencies packages that, surprisingly, had no "modern" packages like: gcc 4.9, zeromq and prime_server.

Right now that's done by [this part of the `paparazzi.sh` script](https://github.com/tangrams/paparazzi/blob/master/paparazzi.sh#L42-L113). Rob is definitely taking this to the next step on making paparazzi a reliable well maintain project! : )

**Comment by tallytalwar** [comment]
`travis` has gcc 4.9.2 support.
Refer: https://github.com/tangrams/tangram-es/blob/master/.travis.yml#L10

**Comment by patriciogonzalezvivo** [comment]
Amazon linux AMI don't : ( we want to make rpm on the flight but test them before hand

**Comment by patriciogonzalezvivo** [comment]
@rmarianski have this almost nailed down. right?

**Comment by rmarianski** [comment]
Yes, I have the dependent rpms built, but don't have a nice workflow for updating in place yet.

**Comment by patriciogonzalezvivo** [comment]
Can we take out the Tangram source on the Cmake/RPM's install?

**Comment by patriciogonzalezvivo** [comment]
Also @rmarianski there is a new member on the **paparazzi** family! Wellcome `paparazzi_proxy` https://github.com/tangrams/paparazzi/commit/3c48add36866f97c8ad1b64b95e19db13e6641e8 Now we need to add it to the RPM magicness... right?

Note: I add compilation/clean/install scripts to `paparazzi.sh`
